name: geektgg
services:
  workerr:
    public: true
    build: .
    replicas: 1
    ports:
      - 8080
    resources:
      cpu: 900m
      memory: 2Gi
    volumes:
      - worker:/data
 
volumes:
  workerr:
    size: 1Gi
